name: "Update release"
on: [repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}': '${{ github.event.client_payload }}'"
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        name: Install/Setup - NIX
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: checkout
        uses: actions/checkout@master
      - name: update
        run: |
          set -x
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          python up.py ${{ github.event.client_payload.release_version }}
        shell: bash
