update-release-deps:
    name: Update release
    on: [repository_dispatch]
    runs-on: ubuntu-latest
    steps:
     - name: Event Information
       run: |
          echo "Event '${{ github.event.action }}' received from '${{ github.event.client_payload }}'"

    - uses: actions/checkout@v2

    - name: Install/Setup - NIX
       - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: update sdist/wheel deps
      - uses: actions/checkout@master
      run: |
        set -x
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        python up.py ${{ github.event.client_payload.release_version }}
      shell: bash
